# -*- coding: utf-8 -*-
"""Unemployment analysis with python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vY8YNSYwJmtZuL3Uhq27H7IdQsC9cV1Q
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly .express as px

from google.colab import files
uploaded = files.upload()

data = pd.read_csv('Unemployment in India.csv')
data

# checking dataset information
data.info()

# describing the dataset
data.describe()

# check null/missing values
data.isnull().sum()

# Count existing columns
print(len(data.columns))

# rename columns, ensuring the number of new names matches the existing number of columns
data.columns = ['States','Date','Frequency','Estimated Unemployment Rate','Estimated Employed','Estimated Labour Participation Rate','Region']

data.head()

# plotting correlation heatmap
import seaborn as sns
import matplotlib.pyplot as plt

plt.style.use('seaborn-whitegrid')
plt.figure(figsize=(8,6))

# Select only numerical columns for correlation calculation
numerical_data = data.select_dtypes(include=['number'])

# Compute the correlation matrix and plot the heatmap
# Assign the result to ax
ax = sns.heatmap(numerical_data.corr(), annot=True,linewidth=3)

# Set tick parameters
ax.tick_params(size=10,color='w',labelsize=10, labelcolor='w')

plt.show()

# plotting histplot

# Correct the number of column names to match the existing number of columns in the DataFrame
data.columns=['States','Date','Frequency','Estimated Unemployment Rate',
                'Estimated Employed','Estimated Labour Participation Rate',
                'Region']
plt.title('Indian Unemployment')
sns.histplot(x='Estimated Employed',hue='Region',data=data)
plt.show()

# plotting histplot

plt.figure(figsize=(10,8))
plt.title("Indian Unemployment")
sns.histplot(x="Estimated Unemployment Rate",hue='Region',data=data)
plt.show()

!pip install plotly
import plotly.express as px

# Group the data by 'Region' and 'States' and aggregate the unemployment rate
unemployment = data.groupby(['Region', 'States'])['Estimated Unemployment Rate'].mean().reset_index()

# Create the sunburst plot
figure = px.sunburst(unemployment, path=['Region','States'],
                     values='Estimated Unemployment Rate',
                     width=700, height=600, color_continuous_scale='RdY1Gn',
                     title="Unemployment Rate in India")
figure.show()

